// Code generated by ObjectBox; DO NOT EDIT.
// Learn more about defining entities and generating this file - visit https://golang.objectbox.io/entity-annotations

package models

import (
	"errors"
	"github.com/google/flatbuffers/go"
	"github.com/objectbox/objectbox-go/objectbox"
	"github.com/objectbox/objectbox-go/objectbox/fbutils"
)

type srcModel_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var SrcModelBinding = srcModel_EntityInfo{
	Entity: objectbox.Entity{
		Id: 3,
	},
	Uid: 2842299620067348701,
}

// SrcModel_ contains type-based Property helpers to facilitate some common operations such as Queries.
var SrcModel_ = struct {
	Id        *objectbox.PropertyUint64
	Protocol  *objectbox.PropertyString
	Address   *objectbox.PropertyString
	Port      *objectbox.PropertyString
	Path      *objectbox.PropertyString
	Url       *objectbox.PropertyString
	CreatedAt *objectbox.PropertyString
	UpdatedAt *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &SrcModelBinding.Entity,
		},
	},
	Protocol: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &SrcModelBinding.Entity,
		},
	},
	Address: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     3,
			Entity: &SrcModelBinding.Entity,
		},
	},
	Port: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     4,
			Entity: &SrcModelBinding.Entity,
		},
	},
	Path: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     5,
			Entity: &SrcModelBinding.Entity,
		},
	},
	Url: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     6,
			Entity: &SrcModelBinding.Entity,
		},
	},
	CreatedAt: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     7,
			Entity: &SrcModelBinding.Entity,
		},
	},
	UpdatedAt: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     8,
			Entity: &SrcModelBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (srcModel_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (srcModel_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("SrcModel", 3, 2842299620067348701)
	model.Property("Id", 6, 1, 4746881662858461100)
	model.PropertyFlags(1)
	model.Property("Protocol", 9, 2, 7237681225176016847)
	model.Property("Address", 9, 3, 7916842376671709873)
	model.Property("Port", 9, 4, 2043476687526791604)
	model.Property("Path", 9, 5, 8129777769187532494)
	model.Property("Url", 9, 6, 8087570224107894457)
	model.Property("CreatedAt", 9, 7, 2803231714610880808)
	model.Property("UpdatedAt", 9, 8, 1198032553794617174)
	model.EntityLastPropertyId(8, 1198032553794617174)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (srcModel_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*SrcModel).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (srcModel_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*SrcModel).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (srcModel_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (srcModel_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*SrcModel)
	var offsetProtocol = fbutils.CreateStringOffset(fbb, string(obj.Protocol))

	var offsetAddress flatbuffers.UOffsetT
	if obj.Address != nil {
		offsetAddress = fbutils.CreateStringOffset(fbb, *obj.Address)
	}

	var offsetPort flatbuffers.UOffsetT
	if obj.Port != nil {
		offsetPort = fbutils.CreateStringOffset(fbb, *obj.Port)
	}

	var offsetPath flatbuffers.UOffsetT
	if obj.Path != nil {
		offsetPath = fbutils.CreateStringOffset(fbb, *obj.Path)
	}

	var offsetUrl flatbuffers.UOffsetT
	if obj.Url != nil {
		offsetUrl = fbutils.CreateStringOffset(fbb, *obj.Url)
	}
	var offsetCreatedAt = fbutils.CreateStringOffset(fbb, obj.CreatedAt)
	var offsetUpdatedAt = fbutils.CreateStringOffset(fbb, obj.UpdatedAt)

	// build the FlatBuffers object
	fbb.StartObject(8)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetProtocol)
	if obj.Address != nil {
		fbutils.SetUOffsetTSlot(fbb, 2, offsetAddress)
	}
	if obj.Port != nil {
		fbutils.SetUOffsetTSlot(fbb, 3, offsetPort)
	}
	if obj.Path != nil {
		fbutils.SetUOffsetTSlot(fbb, 4, offsetPath)
	}
	if obj.Url != nil {
		fbutils.SetUOffsetTSlot(fbb, 5, offsetUrl)
	}
	fbutils.SetUOffsetTSlot(fbb, 6, offsetCreatedAt)
	fbutils.SetUOffsetTSlot(fbb, 7, offsetUpdatedAt)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (srcModel_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'SrcModel' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &SrcModel{
		Id:        propId,
		Protocol:  StreamProtocol(fbutils.GetStringSlot(table, 6)),
		Address:   fbutils.GetStringPtrSlot(table, 8),
		Port:      fbutils.GetStringPtrSlot(table, 10),
		Path:      fbutils.GetStringPtrSlot(table, 12),
		Url:       fbutils.GetStringPtrSlot(table, 14),
		CreatedAt: fbutils.GetStringSlot(table, 16),
		UpdatedAt: fbutils.GetStringSlot(table, 18),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (srcModel_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*SrcModel, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (srcModel_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*SrcModel), nil)
	}
	return append(slice.([]*SrcModel), object.(*SrcModel))
}

// Box provides CRUD access to SrcModel objects
type SrcModelBox struct {
	*objectbox.Box
}

// BoxForSrcModel opens a box of SrcModel objects
func BoxForSrcModel(ob *objectbox.ObjectBox) *SrcModelBox {
	return &SrcModelBox{
		Box: ob.InternalBox(3),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the SrcModel.Id property on the passed object will be assigned the new ID as well.
func (box *SrcModelBox) Put(object *SrcModel) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the SrcModel.Id property on the passed object will be assigned the new ID as well.
func (box *SrcModelBox) Insert(object *SrcModel) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *SrcModelBox) Update(object *SrcModel) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *SrcModelBox) PutAsync(object *SrcModel) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the SrcModel.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the SrcModel.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *SrcModelBox) PutMany(objects []*SrcModel) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *SrcModelBox) Get(id uint64) (*SrcModel, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*SrcModel), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *SrcModelBox) GetMany(ids ...uint64) ([]*SrcModel, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*SrcModel), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *SrcModelBox) GetManyExisting(ids ...uint64) ([]*SrcModel, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*SrcModel), nil
}

// GetAll reads all stored objects
func (box *SrcModelBox) GetAll() ([]*SrcModel, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*SrcModel), nil
}

// Remove deletes a single object
func (box *SrcModelBox) Remove(object *SrcModel) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *SrcModelBox) RemoveMany(objects ...*SrcModel) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the SrcModel_ struct to create conditions.
// Keep the *SrcModelQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *SrcModelBox) Query(conditions ...objectbox.Condition) *SrcModelQuery {
	return &SrcModelQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the SrcModel_ struct to create conditions.
// Keep the *SrcModelQuery if you intend to execute the query multiple times.
func (box *SrcModelBox) QueryOrError(conditions ...objectbox.Condition) (*SrcModelQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &SrcModelQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See SrcModelAsyncBox for more information.
func (box *SrcModelBox) Async() *SrcModelAsyncBox {
	return &SrcModelAsyncBox{AsyncBox: box.Box.Async()}
}

// SrcModelAsyncBox provides asynchronous operations on SrcModel objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type SrcModelAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForSrcModel creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use SrcModelBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForSrcModel(ob *objectbox.ObjectBox, timeoutMs uint64) *SrcModelAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 3, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 3: %s" + err.Error())
	}
	return &SrcModelAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *SrcModelAsyncBox) Put(object *SrcModel) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *SrcModelAsyncBox) Insert(object *SrcModel) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *SrcModelAsyncBox) Update(object *SrcModel) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *SrcModelAsyncBox) Remove(object *SrcModel) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all SrcModel which Id is either 42 or 47:
//
// box.Query(SrcModel_.Id.In(42, 47)).Find()
type SrcModelQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *SrcModelQuery) Find() ([]*SrcModel, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*SrcModel), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *SrcModelQuery) Offset(offset uint64) *SrcModelQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *SrcModelQuery) Limit(limit uint64) *SrcModelQuery {
	query.Query.Limit(limit)
	return query
}

type rtspSrcModel_EntityInfo struct {
	objectbox.Entity
	Uid uint64
}

var RtspSrcModelBinding = rtspSrcModel_EntityInfo{
	Entity: objectbox.Entity{
		Id: 4,
	},
	Uid: 4100077747862286081,
}

// RtspSrcModel_ contains type-based Property helpers to facilitate some common operations such as Queries.
var RtspSrcModel_ = struct {
	Id  *objectbox.PropertyUint64
	Src *objectbox.PropertyString
}{
	Id: &objectbox.PropertyUint64{
		BaseProperty: &objectbox.BaseProperty{
			Id:     1,
			Entity: &RtspSrcModelBinding.Entity,
		},
	},
	Src: &objectbox.PropertyString{
		BaseProperty: &objectbox.BaseProperty{
			Id:     2,
			Entity: &RtspSrcModelBinding.Entity,
		},
	},
}

// GeneratorVersion is called by ObjectBox to verify the compatibility of the generator used to generate this code
func (rtspSrcModel_EntityInfo) GeneratorVersion() int {
	return 6
}

// AddToModel is called by ObjectBox during model build
func (rtspSrcModel_EntityInfo) AddToModel(model *objectbox.Model) {
	model.Entity("RtspSrcModel", 4, 4100077747862286081)
	model.Property("Id", 6, 1, 3051761207703842650)
	model.PropertyFlags(1)
	model.Property("Src", 9, 2, 6391521544834447653)
	model.EntityLastPropertyId(2, 6391521544834447653)
}

// GetId is called by ObjectBox during Put operations to check for existing ID on an object
func (rtspSrcModel_EntityInfo) GetId(object interface{}) (uint64, error) {
	return object.(*RtspSrcModel).Id, nil
}

// SetId is called by ObjectBox during Put to update an ID on an object that has just been inserted
func (rtspSrcModel_EntityInfo) SetId(object interface{}, id uint64) error {
	object.(*RtspSrcModel).Id = id
	return nil
}

// PutRelated is called by ObjectBox to put related entities before the object itself is flattened and put
func (rtspSrcModel_EntityInfo) PutRelated(ob *objectbox.ObjectBox, object interface{}, id uint64) error {
	return nil
}

// Flatten is called by ObjectBox to transform an object to a FlatBuffer
func (rtspSrcModel_EntityInfo) Flatten(object interface{}, fbb *flatbuffers.Builder, id uint64) error {
	obj := object.(*RtspSrcModel)
	var offsetSrc = fbutils.CreateStringOffset(fbb, obj.Src)

	// build the FlatBuffers object
	fbb.StartObject(2)
	fbutils.SetUint64Slot(fbb, 0, id)
	fbutils.SetUOffsetTSlot(fbb, 1, offsetSrc)
	return nil
}

// Load is called by ObjectBox to load an object from a FlatBuffer
func (rtspSrcModel_EntityInfo) Load(ob *objectbox.ObjectBox, bytes []byte) (interface{}, error) {
	if len(bytes) == 0 { // sanity check, should "never" happen
		return nil, errors.New("can't deserialize an object of type 'RtspSrcModel' - no data received")
	}

	var table = &flatbuffers.Table{
		Bytes: bytes,
		Pos:   flatbuffers.GetUOffsetT(bytes),
	}

	var propId = table.GetUint64Slot(4, 0)

	return &RtspSrcModel{
		Id:  propId,
		Src: fbutils.GetStringSlot(table, 6),
	}, nil
}

// MakeSlice is called by ObjectBox to construct a new slice to hold the read objects
func (rtspSrcModel_EntityInfo) MakeSlice(capacity int) interface{} {
	return make([]*RtspSrcModel, 0, capacity)
}

// AppendToSlice is called by ObjectBox to fill the slice of the read objects
func (rtspSrcModel_EntityInfo) AppendToSlice(slice interface{}, object interface{}) interface{} {
	if object == nil {
		return append(slice.([]*RtspSrcModel), nil)
	}
	return append(slice.([]*RtspSrcModel), object.(*RtspSrcModel))
}

// Box provides CRUD access to RtspSrcModel objects
type RtspSrcModelBox struct {
	*objectbox.Box
}

// BoxForRtspSrcModel opens a box of RtspSrcModel objects
func BoxForRtspSrcModel(ob *objectbox.ObjectBox) *RtspSrcModelBox {
	return &RtspSrcModelBox{
		Box: ob.InternalBox(4),
	}
}

// Put synchronously inserts/updates a single object.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the RtspSrcModel.Id property on the passed object will be assigned the new ID as well.
func (box *RtspSrcModelBox) Put(object *RtspSrcModel) (uint64, error) {
	return box.Box.Put(object)
}

// Insert synchronously inserts a single object. As opposed to Put, Insert will fail if given an ID that already exists.
// In case the Id is not specified, it would be assigned automatically (auto-increment).
// When inserting, the RtspSrcModel.Id property on the passed object will be assigned the new ID as well.
func (box *RtspSrcModelBox) Insert(object *RtspSrcModel) (uint64, error) {
	return box.Box.Insert(object)
}

// Update synchronously updates a single object.
// As opposed to Put, Update will fail if an object with the same ID is not found in the database.
func (box *RtspSrcModelBox) Update(object *RtspSrcModel) error {
	return box.Box.Update(object)
}

// PutAsync asynchronously inserts/updates a single object.
// Deprecated: use box.Async().Put() instead
func (box *RtspSrcModelBox) PutAsync(object *RtspSrcModel) (uint64, error) {
	return box.Box.PutAsync(object)
}

// PutMany inserts multiple objects in single transaction.
// In case Ids are not set on the objects, they would be assigned automatically (auto-increment).
//
// Returns: IDs of the put objects (in the same order).
// When inserting, the RtspSrcModel.Id property on the objects in the slice will be assigned the new IDs as well.
//
// Note: In case an error occurs during the transaction, some of the objects may already have the RtspSrcModel.Id assigned
// even though the transaction has been rolled back and the objects are not stored under those IDs.
//
// Note: The slice may be empty or even nil; in both cases, an empty IDs slice and no error is returned.
func (box *RtspSrcModelBox) PutMany(objects []*RtspSrcModel) ([]uint64, error) {
	return box.Box.PutMany(objects)
}

// Get reads a single object.
//
// Returns nil (and no error) in case the object with the given ID doesn't exist.
func (box *RtspSrcModelBox) Get(id uint64) (*RtspSrcModel, error) {
	object, err := box.Box.Get(id)
	if err != nil {
		return nil, err
	} else if object == nil {
		return nil, nil
	}
	return object.(*RtspSrcModel), nil
}

// GetMany reads multiple objects at once.
// If any of the objects doesn't exist, its position in the return slice is nil
func (box *RtspSrcModelBox) GetMany(ids ...uint64) ([]*RtspSrcModel, error) {
	objects, err := box.Box.GetMany(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*RtspSrcModel), nil
}

// GetManyExisting reads multiple objects at once, skipping those that do not exist.
func (box *RtspSrcModelBox) GetManyExisting(ids ...uint64) ([]*RtspSrcModel, error) {
	objects, err := box.Box.GetManyExisting(ids...)
	if err != nil {
		return nil, err
	}
	return objects.([]*RtspSrcModel), nil
}

// GetAll reads all stored objects
func (box *RtspSrcModelBox) GetAll() ([]*RtspSrcModel, error) {
	objects, err := box.Box.GetAll()
	if err != nil {
		return nil, err
	}
	return objects.([]*RtspSrcModel), nil
}

// Remove deletes a single object
func (box *RtspSrcModelBox) Remove(object *RtspSrcModel) error {
	return box.Box.Remove(object)
}

// RemoveMany deletes multiple objects at once.
// Returns the number of deleted object or error on failure.
// Note that this method will not fail if an object is not found (e.g. already removed).
// In case you need to strictly check whether all of the objects exist before removing them,
// you can execute multiple box.Contains() and box.Remove() inside a single write transaction.
func (box *RtspSrcModelBox) RemoveMany(objects ...*RtspSrcModel) (uint64, error) {
	var ids = make([]uint64, len(objects))
	for k, object := range objects {
		ids[k] = object.Id
	}
	return box.Box.RemoveIds(ids...)
}

// Creates a query with the given conditions. Use the fields of the RtspSrcModel_ struct to create conditions.
// Keep the *RtspSrcModelQuery if you intend to execute the query multiple times.
// Note: this function panics if you try to create illegal queries; e.g. use properties of an alien type.
// This is typically a programming error. Use QueryOrError instead if you want the explicit error check.
func (box *RtspSrcModelBox) Query(conditions ...objectbox.Condition) *RtspSrcModelQuery {
	return &RtspSrcModelQuery{
		box.Box.Query(conditions...),
	}
}

// Creates a query with the given conditions. Use the fields of the RtspSrcModel_ struct to create conditions.
// Keep the *RtspSrcModelQuery if you intend to execute the query multiple times.
func (box *RtspSrcModelBox) QueryOrError(conditions ...objectbox.Condition) (*RtspSrcModelQuery, error) {
	if query, err := box.Box.QueryOrError(conditions...); err != nil {
		return nil, err
	} else {
		return &RtspSrcModelQuery{query}, nil
	}
}

// Async provides access to the default Async Box for asynchronous operations. See RtspSrcModelAsyncBox for more information.
func (box *RtspSrcModelBox) Async() *RtspSrcModelAsyncBox {
	return &RtspSrcModelAsyncBox{AsyncBox: box.Box.Async()}
}

// RtspSrcModelAsyncBox provides asynchronous operations on RtspSrcModel objects.
//
// Asynchronous operations are executed on a separate internal thread for better performance.
//
// There are two main use cases:
//
// 1) "execute & forget:" you gain faster put/remove operations as you don't have to wait for the transaction to finish.
//
// 2) Many small transactions: if your write load is typically a lot of individual puts that happen in parallel,
// this will merge small transactions into bigger ones. This results in a significant gain in overall throughput.
//
// In situations with (extremely) high async load, an async method may be throttled (~1ms) or delayed up to 1 second.
// In the unlikely event that the object could still not be enqueued (full queue), an error will be returned.
//
// Note that async methods do not give you hard durability guarantees like the synchronous Box provides.
// There is a small time window in which the data may not have been committed durably yet.
type RtspSrcModelAsyncBox struct {
	*objectbox.AsyncBox
}

// AsyncBoxForRtspSrcModel creates a new async box with the given operation timeout in case an async queue is full.
// The returned struct must be freed explicitly using the Close() method.
// It's usually preferable to use RtspSrcModelBox::Async() which takes care of resource management and doesn't require closing.
func AsyncBoxForRtspSrcModel(ob *objectbox.ObjectBox, timeoutMs uint64) *RtspSrcModelAsyncBox {
	var async, err = objectbox.NewAsyncBox(ob, 4, timeoutMs)
	if err != nil {
		panic("Could not create async box for entity ID 4: %s" + err.Error())
	}
	return &RtspSrcModelAsyncBox{AsyncBox: async}
}

// Put inserts/updates a single object asynchronously.
// When inserting a new object, the Id property on the passed object will be assigned the new ID the entity would hold
// if the insert is ultimately successful. The newly assigned ID may not become valid if the insert fails.
func (asyncBox *RtspSrcModelAsyncBox) Put(object *RtspSrcModel) (uint64, error) {
	return asyncBox.AsyncBox.Put(object)
}

// Insert a single object asynchronously.
// The Id property on the passed object will be assigned the new ID the entity would hold if the insert is ultimately
// successful. The newly assigned ID may not become valid if the insert fails.
// Fails silently if an object with the same ID already exists (this error is not returned).
func (asyncBox *RtspSrcModelAsyncBox) Insert(object *RtspSrcModel) (id uint64, err error) {
	return asyncBox.AsyncBox.Insert(object)
}

// Update a single object asynchronously.
// The object must already exists or the update fails silently (without an error returned).
func (asyncBox *RtspSrcModelAsyncBox) Update(object *RtspSrcModel) error {
	return asyncBox.AsyncBox.Update(object)
}

// Remove deletes a single object asynchronously.
func (asyncBox *RtspSrcModelAsyncBox) Remove(object *RtspSrcModel) error {
	return asyncBox.AsyncBox.Remove(object)
}

// Query provides a way to search stored objects
//
// For example, you can find all RtspSrcModel which Id is either 42 or 47:
//
// box.Query(RtspSrcModel_.Id.In(42, 47)).Find()
type RtspSrcModelQuery struct {
	*objectbox.Query
}

// Find returns all objects matching the query
func (query *RtspSrcModelQuery) Find() ([]*RtspSrcModel, error) {
	objects, err := query.Query.Find()
	if err != nil {
		return nil, err
	}
	return objects.([]*RtspSrcModel), nil
}

// Offset defines the index of the first object to process (how many objects to skip)
func (query *RtspSrcModelQuery) Offset(offset uint64) *RtspSrcModelQuery {
	query.Query.Offset(offset)
	return query
}

// Limit sets the number of elements to process by the query
func (query *RtspSrcModelQuery) Limit(limit uint64) *RtspSrcModelQuery {
	query.Query.Limit(limit)
	return query
}
